### ISSUE TITLE
Test in `test.lua` not passed

### ISSUE THREAD

**Issue by marek094** [ankurhanda/gvnn#26]
Hello, 
I've run tests in gvnn with this result:

`~/gvnn$ th
 
  ______             __   |  Torch7 
 /_  __/__  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ __/ __/ _ \  |  Type ? for help 
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch 
                          |  http://torch.ch 
	
th> require 'gvnn'
{
  VolumetricMaxUnpooling : {...}
  ConcatTable : {...}

  ...

  TemporalRowConvolution : {...}
}
                                                                      [0.0882s]	
th> dofile('test.lua')
	
Testing nn with type = cuda	
	
Running 1 test
1/1 Disparity1D_single .................................................. [WAIT]Illegal instruction (core dumped)`

Runned on: `~/gvnn$ uname -a
Linux ip-172-31-46-126 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
With LuaJIT: `~/gvnn$ luajit -v
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/`

**Comment by marek094** [comment]
Problem does not occur after selecting BitFusion AWS AMI based on Ubuntu 14 from 2016, with properly installed Torch7 and cudnn.

**Comment by ankurhanda** [comment]
That is good to know. I'm sorry you had to go through this struggle. I will soon release tf based code.

**Comment by marek094** [comment]
Would it be possible to say more precisely when you are going to be ready with that (maybe pre-)release? [I have sent you an email did you received it? :)].
