### ISSUE TITLE
Limitation value

### ISSUE THREAD

**Issue by HTLife** [ankurhanda/gvnn#27]
The limit of one_minus_cos_div_theta_sqr is 0.5.
Should [this line](https://github.com/ankurhanda/gvnn/blob/master/TransformationRotationSO3.lua#L296) be 0.5?

From
```lua
one_minus_cos_div_theta_sqr_tensor[b] = one_minus_cos_div_theta_sqr_tensor[b]:fill(0)	
```
to
```lua
one_minus_cos_div_theta_sqr_tensor[b] = one_minus_cos_div_theta_sqr_tensor[b]:fill(0.5)	
```

**Comment by ankurhanda** [comment]
it is not 0.5 I'm sure it is 0.

**Comment by HTLife** [comment]
Did I prove it wrongly?
![_062818_084642_am](https://user-images.githubusercontent.com/4699179/42007007-f0ccb2e4-7aaf-11e8-9396-2a1de587dcb5.jpg)

**Comment by ankurhanda** [comment]
There is omega^2 as well which is multiplied to it.

**Comment by HTLife** [comment]
I got your intention here.
