### ISSUE TITLE
Add to rocks

### ISSUE THREAD

**Issue by Kaixhin** [ankurhanda/gvnn#5]
This look to be pretty comprehensive - do you think it's good to add to the list of Torch [rocks](https://github.com/torch/rocks)?

I've already added it to the [cheatsheet](https://github.com/torch/torch7/wiki/Cheatsheet) for you ;)

**Comment by ankurhanda** [comment]
Thanks :). I'm yet to add lots of other new layers with more examples and demos. Let me sort that out first - I've been a bit lazy with code releases lately :)
