### ISSUE TITLE
about RGB-D VO application in paper

### ISSUE THREAD

**Issue by amiltonwong** [ankurhanda/gvnn#7]
Hi, @ankurhanda ,

In the original paper,  RGB-D VO application is mentioned in section 3. But I could not find the corresponding code in gvnn package. Will it be released later?

**Comment by ankurhanda** [comment]
That was mainly for sanity checking, you can use any off the shelf siamese architecture (or create one inspired from VGG) and stick the SE3 layer at the end like it is shown in the SE3 section in README.md.
